export const hpepTextbooks = [
  {
    title: "The Legislation of Georgia in the Field of Agriculture",
    author: "M.Matiashvili",
    isbn: "6948",
    year: "2009",
  },
  {
    title: "Manufacture of Forages and Nutrition of Animals",
    author: "A.Korakhashvili",
    isbn: "6907",
    year: "2009",
  },
  {
    title: "Technology of Food Production and Processing",
    author: "G.Gogoli",
    isbn: "6970",
    year: "2009",
  },
  {
    title: "Business Management and Global Competition",
    author: "R.Asatiani, S.Asatiani",
    isbn: "475823",
    year: "2009",
  },
  {
    title: "Fundamentals of Agronomics",
    author: "R.Dzidzishvili",
    isbn: "64478",
    year: "2009",
  },
  {
    title: "Water Resources Management in Agriculture",
    author: "I.Kruashvili, I.Inasvili",
    isbn: "47690",
    year: "2009",
  },
  {
    title: "Management of Technological Innovations",
    author: "A.Samadashvili",
    isbn: "4696",
    year: "2009",
  },
  {
    title: "Supervision in Hotel and Restaurant Management",
    author: "M.Vasadze",
    isbn: "7069",
    year: "2009",
  },
  {
    title: "Supervision in Construction and Safety",
    author: "T.Zhordania, Z.Ezugbaia, Sh.Bakanidze",
    isbn: "536478",
    year: "2009",
  },
  {
    title: "Special English (Hotel and Restaurant Management)",
    author: "M.Chkheidze",
    isbn: "364859",
    year: "2009",
  },
  {
    title: "Special English (Small Business)",
    author: "M.Chkheidze",
    isbn: "364782",
    year: "2009",
  },
  {
    title: "Special English (Construction)",
    author: "M.Chkheidze, T.Matchavariani, L.Gogeliani",
    isbn: "356396",
    year: "2009",
  },
  {
    title: "Sales",
    author: "M.Zedgenidze",
    isbn: "65889",
    year: "2009",
  },
  {
    title: "Restaurant Management",
    author: "T.Benidze, M.Vasadze, L.Jejelava",
    isbn: "47589",
    year: "2009",
  },
  {
    title: "Principles of Auditing",
    author: "R.Kutateladze, A.Kobiashvili",
    isbn: "3459",
    year: "2009",
  },
  {
    title: "Mathematics for Business",
    author: "M. Mumladze, S.Tsotniashvili, K.Tsertsvadze",
    isbn: "5869",
    year: "2009",
  },
  {
    title: "Internship in Small Business Administration Specialty",
    author: "არ ფიქსირდება",
    isbn: "47536",
    year: "2009",
  },
  {
    title:
      "Internship in Hotel and Restaurant Business Administration Specialty",
    author: "M.Vasadze",
    isbn: "36488",
    year: "2009",
  },
  {
    title: "Internship in Construction Business Administration Specialty",
    author: "S.Esadze, T.Esadze",
    isbn: "75837",
    year: "2009",
  },
  {
    title: "Hotel Management",
    author: "M.Vasadze",
    isbn: "3558",
    year: "2009",
  },
  {
    title: "General Entrepreneurship",
    author: "G.Erkomaishvili, L.gigauri, N.Talakhadze",
    isbn: "4657",
    year: "2009",
  },
  {
    title: "Fundamentals of Marketing",
    author: "M.Zibzibadze",
    isbn: "37599",
    year: "2009",
  },
  {
    title: "Financial management",
    author: "G.Tsaava",
    isbn: "253478",
    year: "2009",
  },
  {
    title: "Engineering Mechanics",
    author: "T.Batsikadze, V.Pachulia, L.Gogeliani, R.Tskhvedadze",
    isbn: "2547",
    year: "2009",
  },
  {
    title: "E-Commerce",
    author: "K.Maghradze, L.Gogeliani, A.Davitashvili",
    isbn: "36477",
    year: "2009",
  },
  {
    title: "Construction Management",
    author: "G.Tsintsadze",
    isbn: "2353647",
    year: "2009",
  },
  {
    title: "Business Law",
    author: "K.Kokrashvili",
    isbn: "536458",
    year: "2009",
  },
  {
    title: "Construction Materials",
    author: "T.Esadze",
    isbn: "575869",
    year: "2008",
  },
  {
    title: "Surveying",
    author: "M.Tevzadze.S.Tsutskiridze",
    isbn: "63636",
    year: "2008",
  },
  {
    title: "General Management",
    author: "O.Zumburidze",
    isbn: "25366",
    year: "2008",
  },
  {
    title: "Special Events Planning",
    author: "M.Shelia, M.Vasadze, M.Arabuli, M.Kobiashvili.",
    isbn: "36478",
    year: "2008",
  },
  {
    title: "Fundamentals of Accounting",
    author: "M.Dzotsenidze",
    isbn: "354757",
    year: "2008",
  },
  {
    title: "Project Management",
    author: "M.Sulaberidze",
    isbn: "3636",
    year: "2008",
  },
  {
    title: "Technology of Building Pprocesses",
    author: "T.Zhordania, Z.Ezugbaia",
    isbn: "253647",
    year: "2008",
  },
  {
    title: "Customer Service Principles",
    author: "M.Shelia, M.Vasadze, M.Kobiashvili, G.Khomeriki",
    isbn: "53647",
    year: "2008",
  },
  {
    title: "Negotiations",
    author: "M.Chkheidze",
    isbn: "5583",
    year: "2008",
  },
  {
    title: "Mathematics for Business II",
    author: "N.Chechelashvili, L.Chechelashvili",
    isbn: "2465",
    year: "2008",
  },
  {
    title: "Economic of Building",
    author: "J.Chogovadze, R.Pataraia.",
    isbn: "3647",
    year: "2008",
  },
  {
    title: "Business Planning",
    author: "A.Samadashvili",
    isbn: "75431",
    year: "2008",
  },
  {
    title: "Economics",
    author: "A.Katamidze",
    isbn: "9123",
    year: "2008",
  },
  {
    title: "Modern Drafting",
    author: "I.Batsikadze, G.Tsuleiskiri, Z.Kvinikadze, M.Arabidze",
    isbn: "6747",
    year: "2008",
  },
  {
    title: "Leadership",
    author: "I.Zhvania, G.Kiknadze",
    isbn: "3596",
    year: "2008",
  },
  {
    title: "Tourism",
    author: "G.Khomeriki",
    isbn: "5743",
    year: "2008",
  },
  {
    title: "Constructions III (plastic and wood constructions)",
    author: "T.Khmelidze",
    isbn: "453242",
    year: "2008",
  },
  {
    title: "Constructions II (metal constructions)",
    author: "S.Esadze",
    isbn: "25347",
    year: "2008",
  },
  {
    title: "Constructions I (concrete and stone constructions)",
    author: "G.Japaridze",
    isbn: "63787",
    year: "2008",
  },
  {
    title: "Applied Computer Programs III (MS Project, MS FrontPage).",
    author: "A.Davitashvili",
    isbn: "24467",
    year: "2008",
  },
  {
    title: "Applied Computer Programs IV (AutoCAD).",
    author: "M.Kublashvili, N.Pilpani, V.Tchankotadze.",
    isbn: "7674",
    year: "2008",
  },
  {
    title: "Human Resources Management",
    author: "S.Khizanisvili",
    isbn: "13245",
    year: "2008",
  },
  {
    title: "Mathematic for Business",
    author: "Nino Chechelashvili, Lia Chechelashvili, Laura Eliauri",
    isbn: "125435",
    year: "2007",
  },
  {
    title: "Environment and Sustainable Development",
    author: "Nino Pepanashvili, Levan Klimiashvili, Konstantine Maghradze",
    isbn: "2435",
    year: "2007",
  },
  {
    title:
      "Introduction in Computing Technology Part II Ms Excel, Internet explorer, Managing E-mail",
    author: "S.Demurashvili, E.Chikashua, A.Davitashvili",
    isbn: "1324",
    year: "2007",
  },
  {
    title:
      "Introduction in Computing Technology Part I MS Windows, MS Word & MS PowerPoint",
    author: "S.Demurashvili, E.Chikashua, A.Davitashvili",
    isbn: "244",
    year: "2007",
  },
  {
    title: "Culture of Business relations",
    author: "S.Khizanishvili, A.Kulijanashvili, L.Tsikaridze",
    isbn: "321",
    year: "2007",
  },
  {
    title: "International business communication",
    author: "L.Shatakishvili, B.Bestavashvili, Z.Mikadze I.Mikadze",
    isbn: "325",
    year: "2007",
  },
  {
    title: "Effective Business Communication",
    author: "L.Shatakishvili, B.Bestavashvili, Z.Mikadze I.Mikadze",
    isbn: "646226",
    year: "2007",
  },
  {
    title: "Small Business",
    author: "Orjonikidze Nino, Lika Kipiani, Viktoria Bagdasarian",
    isbn: "0000012",
    year: "2007",
  },
  {
    title: "Modern Business",
    author: "Orjonikidze Nino, Lika Kipiani, Viktoria Bagdasarian",
    isbn: "00001",
    year: "2007",
  },
];
