export const hpepGeneral = [
  {
    title: "MARKET LEADER Test File PRE- INTERMEDIATE BUSINESS ENGLISH",
    author: "Christine Johnson",
    isbn: "058277332-1",
    publisher: "LONGMAN",
    year: "2002",
  },
  {
    title: "MARKET LEADER Teacher’s Resource Book PRE- INTERMEDIATE BUSINESS ENGLISH",
    author: "Bill Mascull",
    isbn: "058277332-7",
    publisher: "LONGMAN",
    year: "2002",
  },
  {
    title: "MARKET LEADER Teacher’s Resource Book ELEMENTARY BUSINESS ENGLISH",
    author: "Irene Barrall",
    isbn: "058277332-6",
    publisher: "PEARSON Longman",
    year: "2004",
  },
  {
    title: "MARKET LEADER Course Book PRE- INTERMEDIATE BUSINESS ENGLISH",
    author: "MADavid Cotton",
    isbn: "0-582-50720-0",
    publisher: "PEARSON Longman",
    year: "2002",
  },
  {
    title: "MARKET LEADER Test File INTERMEDIATE BUSINESS ENGLISH",
    author: "Loise Pile",
    isbn: "0-582-83816-9",
    publisher: "PEARSON Longman",
    year: "2005",
  },
  {
    title: "Lernfeld BAUTECHNIC Fachstufen Maurer",
    author: "Christina Alber, BaIder batran",
    isbn: "5628",
    publisher: "HANDWERK UND TECHNIC-HAMBURG",
    year: "2008",
  },
  {
    title: "Grundwissen Bau",
    author: "Batran. Frey. kraus",
    isbn: "8237618678",
    publisher: "HANDWERK UND TECHNIC-HAMBURG",
    year: "2007",
  },
  {
    title: "Concrete principles",
    author: "Thomas P. Fahl",
    isbn: "0-8269-0500-5",
    publisher: "AMERICAN TECHNICAL PUBLISHERS",
    year: "2001",
  },
  {
    title: "Fachwissen Bau",
    author: "maurer, Beton- und Stahlbetonbauer",
    isbn: "978-582-03506-5",
    publisher: "HANDWERK UND TECHNIC-HAMBURG",
    year: "2007",
  },
  {
    title: "Painting Decorating",
    author: "E. Keith Blankenbaker",
    isbn: "1-56637-506-1",
    publisher: "GW",
    year: "2002",
  },
  {
    title: "Tuning Final Report-Toning latin America project 2004-2008",
    author: "Pablo Beneitone Cesar Esquetini",
    isbn: "82435633268",
    publisher: "University of Deusto University of Groningen",
    year: "2007",
  },
  {
    title: "Civil Engineering Education In Europe -2004",
    author: "Edited by Lacint Manoliu",
    isbn: "973-85112-7-5",
    publisher: "INDEPENDENT FILM",
    year: "2004",
  },
  {
    title: "Gas Metal Arc Welding Laboratory Manual",
    author: "Richard Rowe, Larry Jeffus",
    isbn: "0-8273-7609-X",
    publisher: "DELMAR",
    year: "2000",
  },
  {
    title: "Tourism",
    author: "Leonard J.Lickorish, Garson L. Jenkins",
    isbn: "0-7506-1956-2",
    publisher: "B H",
    year: "1997",
  },
  {
    title: "PROJECT MANAGEMENT IN PRACTICE",
    author: "Samuel J. Mantel, Jack R. Meredith",
    isbn: "978-0-470-12164-1",
    publisher: "WILLEY",
    year: "2008",
  },
  {
    title: "Grassroots",
    author: "MARy Joutherm",
    isbn: "65468246824682",
    publisher: "Houghton Mifflin Company",
    year: "2002",
  },
  {
    title: "PRINCIPLES OF AGRIBUSINESS MANAGEMENT",
    author: "James G. Beierlein",
    isbn: "1-57766-267-9",
    publisher: "WAVELAND PRESS, INC",
    year: "2003",
  },
  {
    title: "FARM MANAGEMENT",
    author: "Ronald D. Kay",
    isbn: "0-07-092035-4",
    publisher: "WCB Mc Gray Hill",
    year: "1994",
  },
  {
    title: "Plumbing",
    author: "Michael Loyce",
    isbn: "1-4018-4891-5",
    publisher: "THOMPSON DELMAR LEARNING",
    year: "2005",
  },
  {
    title: "Structural Steel drafting & design",
    author: "David Maclaughin",
    isbn: "1-4018-9032-6",
    publisher: "DELMAR GENGAGE Learning",
    year: "2009",
  },
  {
    title: "THE PRECISION-FARMING GUIDE FOR AGRICULTURISTS",
    author: "John & company",
    isbn: "0-86691-287-8",
    publisher: "Deere & Company",
    year: "2003",
  },
  {
    title: "Plumbing (Workbook)",
    author: "Michael Loyce",
    isbn: "1401848923",
    publisher: "DELMAR GENGAGE Learning",
    year: "2005",
  },
  {
    title: "THE NEW READ-ALOUD HANDBOOk",
    author: "jim Trelease",
    isbn: "546543",
    publisher: "pengguim books",
    year: "1989",
  },
  {
    title: "GoVenture live the Lifeof an Entrepreneur",
    author: "Dell Rogers Mathew Georghiou",
    isbn: "0-13-121580-9",
    publisher: "PEARSON PRENTICE HALL",
    year: "2004",
  },
  {
    title: "MARKET LEADER Practice File PRE- INTERMEDIATE BUSINESS ENGLISH",
    author: "John Rogers",
    isbn: "464654321654",
    publisher: "LONGMAN",
    year: "2001",
  },
  {
    title: "MARKET LEADER Practice File PRE- INTERMEDIATE BUSINESS ENGLISH",
    author: "John Rogers",
    isbn: "549646554",
    publisher: "LONGMAN",
    year: "1999",
  },
  {
    title: "Instructor’s manual with Tests for Essentials of Children’s Literature",
    author: "Carol Lynch-Brown Garl M. Tominson",
    isbn: "0-205-29274-7",
    publisher: "ALLYN AND BACON",
    year: "1999",
  },
  {
    title: "Supplemental Specifications and Recurring Special Provisions",
    author: "არ ფიქსირდება",
    isbn: "1949798949",
    publisher: "IIIions Department of Transportation",
    year: "1999",
  },
  {
    title: "PREPARING VISUAL AIDS FOR PRESENTATIONS",
    author: "Dan Cavanaugh",
    isbn: "79546546549",
    publisher: "ALLYN AND BACON",
    year: "2000",
  },
  {
    title: "HOW 10",
    author: "James L.Clark Lyn R. Clark",
    isbn: "6824642545",
    publisher: "THOMSON SOUTH-WESTERN",
    year: "2004",
  },
  {
    title: "Lernfeld BAUTECHNIC",
    author: "Batran. Frey. kraus",
    isbn: "488784514",
    publisher: "HANDWERK UND TECHNIC-HAMBURG",
    year: "2008",
  },
  {
    title: "Bautechnic Prufungswissen Fur Maurer",
    author: "Frau BarbeI HoIIatz, Wismar",
    isbn: "43248",
    publisher: "Cornelsen",
    year: "2003",
  },
  {
    title: "Bautechnic Fachkunde Bau",
    author: "Frey, Herrmann, Krausewitz",
    isbn: "978-3-8085-4463-1",
    publisher: "EUROPA LEHRMITTEL",
    year: "2008",
  },
  {
    title: "Monitoring Channel MorphoIogy and Bluff Erosion at Two lnstallations of Flow-Deflecting Vanes, North First Greek,Wisconsin, 2000-03",
    author: "U.S. Department of the Interior U.S. Geological Survey",
    isbn: "46846824682",
    publisher: "A.Fitzpatrick, Marie C. peppler",
    year: "2005",
  },
  {
    title: "MARKET LEADER",
    author: "David Cotton, David Faivey",
    isbn: "978-0-4058-1291-7",
    publisher: "PEARSON Longman",
    year: "2007",
  },
  {
    title: "MARKET LEADER",
    author: "John Rogers",
    isbn: "978-0-582-83813-0",
    publisher: "PEARSON PRENTICE HALL",
    year: "2005",
  },
  {
    title: "MARKET LEADER",
    author: "Bill Mascull",
    isbn: "4682",
    publisher: "Pearson Longman",
    year: "2005",
  },
  {
    title: "MARKET LEADER PRE- INTERMEDIATE BUSINESS ENGLISH",
    author: "David Cotton",
    isbn: "96729",
    publisher: "PEARSON Longman",
    year: "არ ფიქსირდება",
  },
  {
    title: "Print Reading For Engineering And Manufacturing Technology",
    author: "David Madsen",
    isbn: "0-8273-5235-2",
    publisher: "DELMAR",
    year: "1995",
  },
  {
    title: "Gases in Entrepreneurship SMALL BUSINESS MANAGEMENT",
    author: "Kirk C. Heriot",
    isbn: "0-13-154272",
    publisher: "PEARSON PRENTICE HALL",
    year: "2003",
  },
  {
    title: "Customer Service",
    author: "Robert W. Lucas",
    isbn: "0-07-800634-1",
    publisher: "Mc Gray Hill",
    year: "2002",
  },
  {
    title: "The Art of Evaluation",
    author: "Tara Fenwick and Jim parsons",
    isbn: "1-55077-104-3",
    publisher: "TEP",
    year: "2000",
  },
  {
    title: "The Art of Evaluation",
    author: "Tara Fenwick and Jim parsons",
    isbn: "1-55077-104-3",
    publisher: "TEP",
    year: "არ ფიქსირდება",
  },
  {
    title: "Managing Human Resources",
    author: "George Bohlander, Scott Snell",
    isbn: "0-324-18405-0",
    publisher: "THOMSON SOUTH-WESTERN",
    year: "2004",
  },
  {
    title: "Human Geography",
    author: "James M. Rubenstein",
    isbn: "0-13-42--142939-6",
    publisher: "PEARSON PRENTICE HALL",
    year: "2005",
  },
  {
    title: "The World of Psychology",
    author: "Daniel Houlihan",
    isbn: "0-205-43419-3",
    publisher: "PEARSON Education",
    year: "2005",
  },
  {
    title: "Engineering Graphics mith AutoCAD 2008",
    author: "James D. Bethune",
    isbn: "0-13-159233-5",
    publisher: "PEARSON PRENTICE HALL",
    year: "2008",
  },
  {
    title: "Making Sense of Adult Learning",
    author: "Dorothy MacKeracher",
    isbn: "0-8020-3778-X",
    publisher: "UTP",
    year: "2006",
  },
  {
    title: "ELECTRONIC COMMERCE",
    author: "Gary P.Schindler",
    isbn: "745455",
    publisher: "COURSE TECNOLOGY GENGAGE",
    year: "2009",
  },
  {
    title: "HP IT Essentials I",
    author: "Cisco Networking Academy",
    isbn: "1-58713-138-2",
    publisher: "Cisco PRESS",
    year: "2003",
  },
  {
    title: "IT Essentials II",
    author: "Cisco Networking Academy",
    isbn: "1-58713-095-5",
    publisher: "Cisco PRESS",
    year: "2003",
  },
  {
    title: "Lab Companion Volume II",
    author: "Cisco Networking Academy Jim Lorenz",
    isbn: "1-58713-030-0",
    publisher: "Cisco PRESS",
    year: "2001",
  },
  {
    title: "Business Plan to Business Reality",
    author: "James R. Skinner",
    isbn: "0-13-039095-X",
    publisher: "PEARSON PRENTICE HALL",
    year: "2003",
  },
  {
    title: "PERSONAL PSYCHOLOGY",
    author: "Rita K. Baltus",
    isbn: "0-02-804294-8",
    publisher: "Glencoe Mc Gray Hill",
    year: "2000",
  },
  {
    title: "Principles of Food, Beverrage, and Labor Cost Controls",
    author: "Paul R.Dittmer, J.Desmond Keefe III",
    isbn: "0-471-42992-9",
    publisher: "WILLEY",
    year: "2006",
  },
  {
    title: "PLUMBING 101",
    author: "Clayton Gregory at al",
    isbn: "1-4283-0522-X",
    publisher: "DELMAR",
    year: "2009",
  },
  {
    title: "The Art of Evaluation (Handbook For Education)",
    author: "Tara Fenwick and Jim parsons",
    isbn: "1-55077-104-3",
    publisher: "TEP",
    year: "2000",
  },
  {
    title: "AgriSelling",
    author: "W.David Downey",
    isbn: "0-932250-32-3",
    publisher: "Dooane Agricutural Services Company",
    year: "1998",
  },
  {
    title: "marketing",
    author: "Gary Armstrong, Philip Kotler",
    isbn: "0-13-142410-6",
    publisher: "PEARSON PRENTICE HALL",
    year: "2005",
  },
  {
    title: "Plumbing Technology:Design and Installation",
    author: "Lee Smith, Michael A. Joyce",
    isbn: "1-4180-5091-1",
    publisher: "THOMPSON DELMAR LEARNING",
    year: "2008",
  },
  {
    title: "The Tourism System",
    author: "Robert Christie Mill",
    isbn: "0-7872-3327-7",
    publisher: "KENDALL/HUNT",
    year: "1998",
  },
  {
    title: "Supervision In The Hospitality Industry",
    author: "Jack E. Miller, Mary Porter",
    isbn: "0-471-19420-4",
    publisher: "WILLEY",
    year: "1998",
  },
  {
    title: "Welcome to Hospitality An Introduction",
    author: "Kye-Sung Chon,Raymond T.Sparrowe",
    isbn: "0-538--70836-0",
    publisher: "SOUTH-WESTERN PUBLISHING CO",
    year: "1995",
  },
  {
    title: "JavaScript",
    author: "Don Gosselin",
    isbn: "0-619-06334-3",
    publisher: "COURSE TECHNOLOGY THOMPSON LEARNING",
    year: "2002",
  },
  {
    title: "Managing Behavior in Organizations",
    author: "Jerald Greenberg",
    isbn: "0-13-144746-7",
    publisher: "PEARSON PRENTICE HALL",
    year: "2005",
  },
  {
    title: "Masonry Skills",
    author: "Richard T.Kreh",
    isbn: "978-1-4180-3753-6",
    publisher: "THOMPSON DELMAR LEARNING",
    year: "2008",
  },
  {
    title: "Modern Carpentry",
    author: "Willis H.Wagner",
    isbn: "1-56637-569-X",
    publisher: "GW",
    year: "1996",
  },
  {
    title: "Business Law",
    author: "Arnold J. Goldman",
    isbn: "0-9-618-73155-5",
    publisher: "Houghton Mifflin Company",
    year: "2007",
  },
  {
    title: "ECONOMICS",
    author: "McConnell, Brue",
    isbn: "0-07-047094-4",
    publisher: "Mc Gray Hill",
    year: "1999",
  },
  {
    title: "Environmental Engineering",
    author: "Mackenzie L. Davis David A.Cornwell",
    isbn: "4123132",
    publisher: "Mc Gray Hill",
    year: "2008",
  },
  {
    title: "Carpentery",
    author: "Floyd Vogt, Michael Nauth",
    isbn: "0-17-610526-3",
    publisher: "NELSON",
    year: "2009",
  },
  {
    title: "Building Construction Illustrated",
    author: "Francis D. K. Ching",
    isbn: "897-0-470-0807-781-7",
    publisher: "WILLEY",
    year: "2008",
  },
  {
    title: "Hydrology and Hydraulic Systems",
    author: "Ram S. Gupta",
    isbn: "1-57766-173-7",
    publisher: "WAVELAND,PRESS,INC",
    year: "2001",
  },
  {
    title: "E-Business and E-Commerce Management",
    author: "Dave Chaffey",
    isbn: "0-273-7072-3",
    publisher: "FT Prentice Hall",
    year: "2007",
  },
  {
    title: "Civiel And Environmental Systems Engineering",
    author: "Charles S. Revelle",
    isbn: "0-13-047822-9",
    publisher: "PEARSON PRENTICE HALL",
    year: "2004",
  },
  {
    title: "Dialogues An Argument Rhetoric and Reader",
    author: "Gary Goshgarian Kathleen Krueger",
    isbn: "0-321-10146-4",
    publisher: "longman",
    year: "2003",
  },
  {
    title: "AutoCAD Architecture 2008",
    author: "H. Edward Coldberg",
    isbn: "0-13-159227-0",
    publisher: "PEARSON PRENTICE HALL",
    year: "2007",
  },
  {
    title: "AGRICULTURAL ENGINEERING CENTURU",
    author: "Iova State University",
    isbn: "0-000-0000",
    publisher: "Howard P. Johnson",
    year: "2005",
  },
  {
    title: "AutoCAD 2008 in 2D and 3D",
    author: "Paul Richard. frank E. Puerta",
    isbn: "0-13-514373-X",
    publisher: "PEARSON PRENTICE HALL",
    year: "2008",
  },
  {
    title: "Marriages and Families making Choices in a Diverse Society",
    author: "Kenrick S.Thompson",
    isbn: "0-534-58889-1",
    publisher: "THOMSON WADSWORTH",
    year: "2003",
  },
  {
    title: "NEW VENTYRE CREATION",
    author: "Jeffry A. Timmons, Stephen Spinelli",
    isbn: "0-07-310279-2",
    publisher: "Mc Gray Hill",
    year: "2007",
  },
  {
    title: "What Color is your Parachute?",
    author: "Richard Nelson Bolles",
    isbn: "978-1-58008-930-2",
    publisher: "Ten Speed Press",
    year: "2009",
  },
  {
    title: "SCHOLARSHIP RECONSIDERED",
    author: "Ernest L. Boyer",
    isbn: "0-7879-4069-0",
    publisher: "GF",
    year: "1990",
  },
  {
    title: "Patterns For College Writing",
    author: "Laurie G. Kirszner",
    isbn: "0-312-19044-1",
    publisher: "ST.MARTIN’ S",
    year: "1998",
  },
  {
    title: "Entrepreneurship",
    author: "Steve Mariotti",
    isbn: "0-13-119767-3",
    publisher: "PEARSON PRENTICE HALL",
    year: "2007",
  },
  {
    title: "Building a Dream",
    author: "Walter S.Good",
    isbn: "0-07-089810-3",
    publisher: "Mc Gray Hill",
    year: "2003",
  },
  {
    title: "Financial Accounting",
    author: "Kimmel Weygandt Kieso",
    isbn: "0-471-41578-2",
    publisher: "WILLEY",
    year: "2004",
  },
  {
    title: "Entrepreneurial Marketing",
    author: "Bruce Buskirk, Molly Lavik",
    isbn: "0-324-15863-7",
    publisher: "THOMSON SOUTH-WESTERN",
    year: "2004",
  },
  {
    title: "Plant Science",
    author: "Margaret J.McMahon",
    isbn: "0-13-114075-2",
    publisher: "PEARSON PRENTICE HALL",
    year: "2007",
  },
  {
    title: "Small Business Managment",
    author: "JUSTIN G. LONGENECKER LEO B. DONLEVY",
    isbn: "0-17-640724-3",
    publisher: "Thompson,Nelson",
    year: "2007",
  },
  {
    title: "SUPERVISION",
    author: "Edvin C. Leonard",
    isbn: "0-324-17881-6",
    publisher: "Thompson, South-Western",
    year: "2004",
  },
  {
    title: "Plastering Skills",
    author: "F.Van Den Branden",
    isbn: "0-8269-0657-5",
    publisher: "ATP",
    year: "1984",
  },
  {
    title: "SELLING TODAY",
    author: "GERALD L. MANNING BARRY L. REECE",
    isbn: "0-13-127599-2",
    publisher: "Person Prentice Hall",
    year: "2007",
  },
  {
    title: "Masonry Skills",
    author: "Ricard T. Kreh, Sr",
    isbn: "0-7668-5936-3",
    publisher: "THOMPSON",
    year: "2003",
  },
  {
    title: "English For Careers",
    author: "Leila R. Smith",
    isbn: "0-13-192130-4",
    publisher: "Person Prentice Hall",
    year: "2006",
  },
  {
    title: "Principles of Marketing",
    author: "Philip Kotler Gary Armstrong",
    isbn: "842684",
    publisher: "Pearson",
    year: "2008",
  },
  {
    title: "Instructors Resource Manual",
    author: "Leslie A . Swetnam",
    isbn: "0-618-30705-2",
    publisher: "Houghton mifflin",
    year: "2004",
  },
  {
    title: "Masonry",
    author: "Robert Ham",
    isbn: "1-4180-5284-1",
    publisher: "THOMPSON",
    year: "2008",
  },
  {
    title: "Elementary Language Practice",
    author: "Michael Vince",
    isbn: "978-1-4050-0764-1",
    publisher: "Macmillan",
    year: "2003",
  },
  {
    title: "Scholarship Assessed\n",
    author: "Charles E. Classic, Mary Taylor Huber\n",
    isbn: "0-7879-1091-0\n",
    publisher: "Jossey-Bass Publishers\n",
    year: "1997",
  },
  {
    title: "Construction Methods and Management\n",
    author: "S.W. Nunnally\n",
    isbn: "0-13-085962-1\n",
    publisher: "PRENTICE HALL\n",
    year: "2001",
  },
  {
    title: "Agricultural Economics and Agribusiness\n",
    author: "Gail L. Gramer, Clarence W. Jensen\n",
    isbn: "0-471-38847-5\n",
    publisher: "WILLEY",
    year: "2001\n",
  },
  {
    title: "Business English",
    author: "Mary Ellen Guffey\n",
    isbn: "0-324-12154-7\n",
    publisher: "SOUTH-WESTERN\n",
    year: "2002",
  },
  {
    title: "Reinforced Concrete Tecnology\n",
    author: "Samuel E. French\n",
    isbn: "0-8273-5495-9\n",
    publisher: "Delmar",
    year: "1994",
  },
  {
    title: "Hydrology and Hydraulic Sysstems\n",
    author: "Ram S. Cupta\n",
    isbn: "1-57766-030-7\n",
    publisher: "Waveland",
    year: "2001",
  },
  {
    title: "Fundamentals of Fluid Mechanics\n",
    author: "Bruce R. Munson\n",
    isbn: "0-471-667582-2\n",
    publisher: "WILEY",
    year: "2006",
  },
  {
    title: "Fundamentals of Fluid Mechanics (To Accompany)\n",
    author: "Bruce R. Munson\n",
    isbn: "0-471-71896-3\n",
    publisher: "WILEY\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Dam Hydraulics\n",
    author: "D.L.Vischer,W.H.Hager\n",
    isbn: "0-471-97289-4\n",
    publisher: "WILLEY",
    year: "1998",
  },
  {
    title: "Building Trades Dictionary\n",
    author: "Leonard P.Toenges\n",
    isbn: "0-8269-0405-x\n",
    publisher: "ATP",
    year: "არ ფიქსირდება",
  },
  {
    title: "Practing College Study Skills\n",
    author: "Carolyn H.Hopper\n",
    isbn: "0-618-04665-8\n",
    publisher: "Houghton Mifflin Company\n",
    year: "2001",
  },
  {
    title: "Fundamentals of Modern Drafting\n",
    author: "Paul Ross Wallach\n",
    isbn: "1-4018-0946-4\n",
    publisher: "THOMSON",
    year: "2003",
  },
  {
    title: "Physical Geology\n",
    author: "Charles C.Plummer\n",
    isbn: "0-697-13807-0\n",
    publisher: "WCB",
    year: "1993",
  },
  {
    title: "Marriages and Families\n",
    author: "Mary Ann Lamanna A. Riedmann\n",
    isbn: "0534588875",
    publisher: "THOMSON WADSWORTH\n",
    year: "2003",
  },
  {
    title: "International business\n",
    author: "John J. Wild, Kenneth L. Wild\n",
    isbn: "68243846246",
    publisher: "Prentice Hall\n",
    year: "2001\n",
  },
  {
    title: "Reinforced Concrete\n",
    author: "James K. Wight\n",
    isbn: "0-13-207474-5\n",
    publisher: "Pearson Prentice Hall\n",
    year: "2009\n",
  },
  {
    title: "Creating Significant Learni9ng Experiences\n",
    author: "JB",
    isbn: "0-7879-6055-1\n",
    publisher: "L. Dee Fink\n",
    year: "2003\n",
  },
  {
    title: "Farm Power and Machinery Management\n",
    author: "Donnell Hunt\n",
    isbn: "1-57766-573-2\n",
    publisher: "WAVELAND,PRESS,INC\n",
    year: "2001",
  },
  {
    title: "Confidence in Public Speakivg\n",
    author: "Paul E.Nelson\n",
    isbn: "0-07-229577-5\n",
    publisher: "McGraw-Hill\n",
    year: "1998",
  },
  {
    title: "Business Comunication\n",
    author: "Krizan, Merrier, Jones\n",
    isbn: "787248\n",
    publisher: "South-Western,Thompson\n",
    year: "2002",
  },
  {
    title: "Supervision in the hospitality industry\n",
    author: "Jach E. Miller, John R. Walker\n",
    isbn: "0-471-39689-3\n",
    publisher: "WILLEY",
    year: "2002",
  },
  {
    title: "Instructor s Re source Manual with Test Bank\n",
    author: "Kenrich S. Thompson\n",
    isbn: "0-534-58892-1\n",
    publisher: "THOMSON WADSWORTH\n",
    year: "2003",
  },
  {
    title: "Chemistry in Context Applying Chemisstry to Society\n",
    author: "Conard L. Stanitski\n",
    isbn: "0-07-241015-9\n",
    publisher: "Mc Gray Hill\n",
    year: "2003",
  },
  {
    title: "Economics Teory and Practice\n",
    author: "Pathrick J.Welch\n",
    isbn: "0-03-006648-4\n",
    publisher: "DRYDEN\n",
    year: "1995\n",
  },
  {
    title: "Electronic Commerce\n",
    author: "Thompson COURSE TECHNOLOGY\n",
    isbn: "0-619-15955-3\n",
    publisher: "Gary P. Shneider\n",
    year: "2003",
  },
  {
    title: "Standard Specifications For Road And Bridge Construction\n",
    author: "არ ფიქსირდება",
    isbn: "0-07-242457-9\n",
    publisher: "Iiiinois Department Of Transportation\n",
    year: "2002",
  },
  {
    title: "International Business THE CHALANGES OF GLOBALIZATION\n",
    author: "John J. Wild Kenneth L. Wild Jerry C.Y. Han\n",
    isbn: "0-13-143275-3\n",
    publisher: "PEARSON PRENTICE HALL\n",
    year: "2006\n",
  },
  {
    title: "Principles Of Microeconomics\n",
    author: "JOHN E. SAYRE ALAN J. MORRIS\n",
    isbn: "0-07-094641-8\n",
    publisher: "Mcgraw-Hill Ryerson\n",
    year: "2006",
  },
  {
    title: "Design And Control Of Concrete Mixtures\n",
    author: "Steven H. Kosmatka Beatrix Kerkhoff William C. Panarese Norman F. Macleod Richard J. Mcgrath\n",
    isbn: "0-89312-218-1\n",
    publisher: "Cement Association Of Canada\n",
    year: "2002",
  },
  {
    title: "Course Options Exercises\n",
    author: "Jane F.James. Swarthmoe College Information Services\n",
    isbn: "26846454",
    publisher: "Center For Teaching And Learning\n",
    year: "2001",
  },
  {
    title: "Course Tools Exercises\n",
    author: "Jane F.James. Swarthmoe College Information Services\n",
    isbn: "4162876825\n",
    publisher: "Center For Teaching And Learning\n",
    year: "2003",
  },
  {
    title: "Laboratory Manual CHEMISTRY In CONTEXT Applying Chemistry To Society\n",
    author: "Conrad L.Stanitski\n",
    isbn: "0-07-242457-5\n",
    publisher: "Mc Graw Higher Education Hill\n",
    year: "2003",
  },
  {
    title: "Course Content Exeecises\n",
    author: "Jane F.James. Swarthmoe College Information Services\n",
    isbn: "27842668422358",
    publisher: "Center For Teaching And Learning\n",
    year: "2004",
  },
  {
    title: "Overview",
    author: "არ ფიქსირდება",
    isbn: "76812862485",
    publisher: "Center For Teaching And Learning\n",
    year: "2003",
  },
  {
    title: "Assessment Exercises\n",
    author: "არ ფიქსირდება",
    isbn: "824685",
    publisher: "Center For Teaching And Learning\n",
    year: "2002",
  },
  {
    title: "GIS An D Natural Resources Management\n",
    author: "არ ფიქსირდება",
    isbn: "24455245255",
    publisher: "Agricultural And Biosystems Engineering Iowa State University\n",
    year: "2002",
  },
  {
    title: "Laboratory Manual CHEMISTRY In CONTEXT Applying Chemistry To Society\n",
    author: "Wilmer J.Stratton\n",
    isbn: "0-07-242457-5\n",
    publisher: "Mc Graw Higher Education Hill\n",
    year: "2003",
  },
  {
    title: "INFORMATION TECHNOLOGY MANAGEMENT Agricultural Systems Technologet\n",
    author: "Iowa State University BOOK STORE\n",
    isbn: "7487625",
    publisher: "lnstructor:Dr.U. Sunday Tim\n",
    year: "2003",
  },
  {
    title: "Up To Speed: Computers For Family Learning Progect Report And Curriculum Guide\n",
    author: "Chilliwack B.C.\n",
    isbn: "5246425",
    publisher: "University College Of The Fraser Valley\n",
    year: "2001",
  },
  {
    title: "Web Trak Promoting Your Web Site\n",
    author: "Robin Nobles\n",
    isbn: "2384654165",
    publisher: "CCI Learning Solutions Inc.\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Solutions Manual For Environmental Chemistry\n",
    author: "Colin Baird\n",
    isbn: "0-7167-3435-4\n",
    publisher: "W.H. Freeman And Company NEW YORK\n",
    year: "2000",
  },
  {
    title: "CLASSROOM ASSESSMENT TECHNIQUES A Handbook For College Teachers\n",
    author: "Thomas A.Angelo\n",
    isbn: "1-55542-500-3\n",
    publisher: "Jossey-Bass Publishers San Francisco\n",
    year: "1993",
  },
  {
    title: "Carpenter Apprentichip Program Year 1-Frame residential Housing\n",
    author: "არ ფიქსირდება",
    isbn: "54368",
    publisher: "Selkrik Coolege\n",
    year: "2004",
  },
  {
    title: "Carpenter Apprenticeship Program Year 1-Build Concrete Formwork\n",
    author: "არ ფიქსირდება",
    isbn: "827622465",
    publisher: "Selkrik Coolege\n",
    year: "2004\n",
  },
  {
    title: "Carpenter Apprenticeship Program Year 1-Site Layoyots\n",
    author: "არ ფიქსირდება",
    isbn: "4628462465",
    publisher: "Selkirk College\n",
    year: "2004",
  },
  {
    title: "Becing A Master Students ELLIS\n",
    author: "არ ფიქსირდება",
    isbn: "0-359-69293-8\n",
    publisher: "Houghton Mifflin\n",
    year: "1994",
  },
  {
    title: "Carpenter Apprenticeship Program Yearl-Safe Work Practices\n",
    author: "არ ფიქსირდება",
    isbn: "35465432546",
    publisher: "Selkirk College\n",
    year: "2004",
  },
  {
    title: "Carpenter Apprenticeship Program Year 1-Drawing And Specification Interpretation\n",
    author: "არ ფიქსირდება",
    isbn: "546287426",
    publisher: "Selkirk College\n",
    year: "2004",
  },
  {
    title: "Carpenter Apprenticeship Program Year 1-Portable Power Tools\n",
    author: "არ ფიქსირდება",
    isbn: "4654235463",
    publisher: "Selkrik College\n",
    year: "2004",
  },
  {
    title: "Carpenter Apprenticeship Program Yearl-Hand Tools",
    author: "არ ფიქსირდება",
    isbn: "8612654236541",
    publisher: "Selkrik Coolege\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "POLLUTION",
    author: "David L.Bender\n",
    isbn: "1-56510-075-1\n",
    publisher: "Current Controversies\n",
    year: "1994",
  },
  {
    title: "Carpenter Apprenticeship Program Year Shop Equipment\n",
    author: "არ ფიქსირდება",
    isbn: "154135432",
    publisher: "Selkrik Coolege\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Carpenter Apprenticeship Program Year Use Ladders And Scaffolds\n",
    author: "არ ფიქსირდება",
    isbn: "416354054",
    publisher: "Selkirk College\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Carpenter Apprenticeship Program Year Materials Identification\n",
    author: "არ ფიქსირდება",
    isbn: "15461543541235",
    publisher: "Selkirk College\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Teaching And The Case Method\n",
    author: "Louisb.Barnes C Roland Chrissen Abby J.Hansen\n",
    isbn: "0-8584-403-0\n",
    publisher: "Harvard Business School Press\n",
    year: "1994",
  },
  {
    title: "Work To Accompany Carpentry\n",
    author: "Floyd Vogt\n",
    isbn: "1-4018-7070-8\n",
    publisher: "Thomson",
    year: "2206",
  },
  {
    title: "Carpentry\n",
    author: "Floyd Vogt\n",
    isbn: "1-4018-7069-4\n",
    publisher: "Thomson",
    year: "2006",
  },
  {
    title: "Clobal Environmental Issues A Climatological Approach\n",
    author: "David Kemp\n",
    isbn: "0-415-10309-6\n",
    publisher: "Routledge",
    year: "1994",
  },
  {
    title: "Fundamental Accounting Principles Volume II\n",
    author: "Kermit D. Larson Tilly Jensen\n",
    isbn: "0-07-091652-7\n",
    publisher: "Mcgraw-Hill Ryerson\n",
    year: "2003",
  },
  {
    title: "INTRODUCTION TO ENVIRONMENTAL ENGINEERING AND SCIENCE\n",
    author: "Gilbert Masters\n",
    isbn: "0-13-483066-0\n",
    publisher: "PRENTICE HALL Englewood Cliffs, New Jersey\n",
    year: "1991",
  },
  {
    title: "Fundamental Accounting Principles Volume II\n",
    author: "Kermit D. Larson Tilly Jensen\n",
    isbn: "0-07-091649-7\n",
    publisher: "Mcgraw-Hill Ryerson\n",
    year: "2003",
  },
  {
    title: "Java Script Bible\n",
    author: "Danny Goodman\n",
    isbn: "0-7645-3188-3\n",
    publisher: "IDG Books Worldwide\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Tools And Methods For The Improvement Of Quality\n",
    author: "Howard Gitlow\n",
    isbn: "0-256-05680-3\n",
    publisher: "IRWIN Homewood JL Boston\n",
    year: "1989",
  },
  {
    title: "Canadian Human Resource Management\n",
    author: "Hermann Schwind, Hari DAS,Terry Wagar\n",
    isbn: "0-07-091718-3\n",
    publisher: "Mcgraw-Hill Ryerson\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Microsoft Office Access 2003\n",
    author: "Gary B. Shelly Thomas J. Cashman Philip J. Pratt Mary Z. Last\n",
    isbn: "1-4188-4362-8\n",
    publisher: "Thompson COURSE TECHNOLOGY\n",
    year: "2003",
  },
  {
    title: "Implementation Theory And Practice\n",
    author: "Malcolm Goggin\n",
    isbn: "0-673-39692-4\n",
    publisher: "Harper Collins Publishers\n",
    year: "1990",
  },
  {
    title: "EPIM05",
    author: "COUNCIL OF EUROPE\n",
    isbn: "654135154",
    publisher: "არ ფიქსირდება",
    year: "არ ფიქსირდება",
  },
  {
    title: "Mckeachie's Teaching Tips",
    author: "Wlbert J. Mckeachie",
    isbn: "0-618-11649-4\n",
    publisher: "Houghton Mifflin\n",
    year: "2002",
  },
  {
    title: "Concrete Formwork\n",
    author: "Leonard Koel\n",
    isbn: "0-8269-0708-3\n",
    publisher: "Amer Technical Pub\n",
    year: "არ ფიქსირდება",
  },
  {
    title: "Microsoft Office Excel 2003\n",
    author: "Gary B. Shelly Thomas J.Cashman James S.Quasney\n",
    isbn: "1-4188-4360-1\n",
    publisher: "Thompson COURSE TECHNOLOGY\n",
    year: "2006",
  },
  {
    title: "Microsoft Word 2003 Specialist\n",
    author: "Nita Hewitt Rutkosky\n",
    isbn: "0-7638-2064-4\n",
    publisher: "EMC/Paradigm Publishing\n",
    year: "არ ფიქსირდება",
  },
]
